<?php

namespace Mosolov\Datastructure;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-25 at 19:57:55.
 */
class DoublyLinkedListTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DoublyLinkedList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DoublyLinkedList();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Mosolov\Datastructure\DoublyLinkedList::sort
     * @todo   Implement testSort().
     */
    public function testSort() {
        $this->assertCount(0, $this->object);
        $this->object->sort();
        // list has only one node
        // sort operation must not be executed
        // so no need check the value of node
        $this->object->push('Bad value, not implemented Mosolov\Datastructure\Node\ICompare ');
        $this->object->sort();
        $this->assertCount(1, $this->object);
        
        $this->object->push('Another bad value');
        $this->setExpectedException(
          'RuntimeException',
          DoublyLinkedList::EX_MSG_UNSORTABLE_NODE_DETECTED,
          DoublyLinkedList::EX_CODE_UNSORTABLE_NODE_DETECTED
        );
        $this->object->sort();
    }

}
